stages:
  - test
  - build
  - delivery
  - deploy

image: python:3

unittest:
  stage: test
  before_script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install -U pip
    - export PYTHONPATH="$PYTHONPATH:$(pwd)"
    - pip install -r requirements.txt
  script:
    - pytest -s tests/unit_tests/
  only:
    - master

coverage:
  extends: unittest
  script:
    - pip install pytest-cov
    - pytest --cov=basicmlapp tests/unit_tests/ | tee coverage/coverage.txt
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/" # This parses the coverage log to display coverage into gitlab
  only:
    - master

# exemple d'un autre test possible
# check linting:
#   extends: test
#   script:
#     - make lint

# build:
#   stage: build
#   before_script:
#     - python3 -m venv .venv
#     - source .venv/bin/activate
#     - pip install -U pip
#     - export PYTHONPATH="$PYTHONPATH:$(pwd)"
#     - pip install -r requirements.txt
#   script:
#     - pytest -s tests/unit_tests/
#   only:
#     - master
