stages:
  - test
  - build
  - delivery
  - deploy

image: python:3

unittest:
  stage: test
  before_script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install -U pip
    - export PYTHONPATH="$PYTHONPATH:$(pwd)"
    - pip install -r requirements.txt
  script:
    - pytest -s tests/unit_tests/

# check linting:
#   extends: test
#   script:
#     - make lint

coverage:
  extends: test
  script:
    - pip install pytest-cov
    - pytest --cov=basicmlapp tests/unit_tests/
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/" # This parses the coverage log to display coverage into gitlab

  ## DEPLOY

# deploy:
#   stage: deploy
#   before_script:
#     - mkdir -p ~/.ssh
#     - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
#     - chmod 600 ~/.ssh/id_rsa
#     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
#   script:
#     - bash .gitlab-deploy.sh
#   when: manual
